// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrKq27tjxZy2wYM6JLaUT7a17Y5P6X_1g',
    appId: '1:563091470993:web:a2b469b309e3f5fc1d5d30',
    messagingSenderId: '563091470993',
    projectId: 'real-estate-f6a44',
    authDomain: 'real-estate-f6a44.firebaseapp.com',
    storageBucket: 'real-estate-f6a44.appspot.com',
    measurementId: 'G-NMLF8W191M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR1w_vU9i5_8UreL1CusVRlWn9WhXnRTk',
    appId: '1:563091470993:android:c0b677e3e9fa23241d5d30',
    messagingSenderId: '563091470993',
    projectId: 'real-estate-f6a44',
    storageBucket: 'real-estate-f6a44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPODOMg74vM0uQydv2zqeLA4Jg2AI2RrU',
    appId: '1:563091470993:ios:ae18e89e58d5d4241d5d30',
    messagingSenderId: '563091470993',
    projectId: 'real-estate-f6a44',
    storageBucket: 'real-estate-f6a44.appspot.com',
    iosClientId: '563091470993-k0ag0udnf37hieusuv6b6jgf4lc3645q.apps.googleusercontent.com',
    iosBundleId: 'com.example.justhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPODOMg74vM0uQydv2zqeLA4Jg2AI2RrU',
    appId: '1:563091470993:ios:ae18e89e58d5d4241d5d30',
    messagingSenderId: '563091470993',
    projectId: 'real-estate-f6a44',
    storageBucket: 'real-estate-f6a44.appspot.com',
    iosClientId: '563091470993-k0ag0udnf37hieusuv6b6jgf4lc3645q.apps.googleusercontent.com',
    iosBundleId: 'com.example.justhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrKq27tjxZy2wYM6JLaUT7a17Y5P6X_1g',
    appId: '1:563091470993:web:30ff7f4b236c73931d5d30',
    messagingSenderId: '563091470993',
    projectId: 'real-estate-f6a44',
    authDomain: 'real-estate-f6a44.firebaseapp.com',
    storageBucket: 'real-estate-f6a44.appspot.com',
    measurementId: 'G-VZWKWG68N7',
  );

}